---
title: "Stat120: Introduction to Statistics"
subtitle: "Spring 2026"
execute:
  freeze: true
typst-logo:
  path: "logo.png"
format: 
  html: default
  syllabus-typst: default
---


::: {.boxed-text}

| | | |
|:----------------|:-------------------------------------------|:-----------------|
| **MEETINGS:** | MWF 3a                                    | **CMC 102** |
|                 | 11:10-12:20 MW; 12-1 F                     |                  |
| **PROFESSOR:** | Amanda Luby                               | **CMC 223** |
|                 | aluby\@carleton                            |                  |
| **DROP-IN:** | Mon 3-4pm                                 | **CMC 307** |
|                 | Tues 2-3                                  |                  |
|                 | Wed 9:30-10:30 (120 priority)             |                  |
|                 | Fri 10-11 (230 priority)                  |                  |
|                 | Or by appointment!                         |                  |
| **WEBSITE:** | [moodle.carleton.edu](https://moodle.carleton.edu) |          |
| **TEXT:** | *Statistics: Unlocking the Power of Data* By Lock, Lock, Lock, Lock, and Lock (yes there's 5 of them!) |                  |
|                 | *Stat120 Lab Manual*: math.carleton.edu/RLabManual/       |                  |
| **SOFTWARE:** | [maize.mathcs.carleton.edu](https://maize.mathcs.carleton.edu) | |

: {tbl-colwidths="[30,50,20]"}

:::

```{=typst}
#colbreak()
```

# Course Description

Stat120 serves as an introduction to statistics and data analysis. Practical aspects of statistics will be emphasized, including extensive use of programming in the statistical software R, interpretation and communication of results. Topics include: exploratory data analysis, correlation and linear regression, design of experiments, the normal distribution, randomization approach to inference, sampling distributions, estimation, and hypothesis testing. 

# Course Objectives

Statistical literacy is a key skill for many different courses and majors, and necessary to be a responsible citizen in the “real world”. In this course, we will lay the foundations for statistical literacy and learn basic data analysis skills. Upon successful completion of the course, students are expected to be able to:

- Work with and describe various types of data
- Understand the role of variation and randomness and the principles of statistical inference
- Choose the appropriate statistical analysis for a given task and recognize when certain statistical analyses are not appropriate
- Analyze data and apply statistical methods using R and interpret results
- Critically examine analyses of data and interpretations of results from statistical methods 

There are no prerequisites for this course, and you do not need to have any background in statistics, mathematics, or computer science to do well in this course. 

If you’ve already taken Math 211, Psych 200, Psych 201, SOAN 239, Math 240 or Stat 250, a different statistics class may be more appropriate for you. Please reach out if this is the case. 

# Course Components

## Meetings

There will be three course meetings per week (Mondays, Wednesdays, and Fridays). Daily attendance is expected. Course meetings will combine demonstrations using R, theoretical background, and in-class group exercises. On most days, I’ll ask you to complete a reading or watch a short video before class, as well as complete a “daily check in” on gradescope before class. Late completions will not be accepted, but I will drop your lowest 3 when computing your final grade.

## Individual Assignments

Homework will be assigned once per week (typically due Wednesdays or Fridays) and should be submitted on gradescope by 10pm — this is the time that Stat Lab Sessions end on weekdays. There is a 12-hour grace period for each assignment. If you are ill or have an emergency, please contact me to arrange an alternative due date. Assignment submissions should be neatly written and scanned or submitted as a PDF file. You must show all work to receive credit. 

## Midterm Exams

A key part of statistical literacy is being able to recall concepts “on the fly”. I use in-class exams to assess your understanding of class material without access to resources. There will be three midterm exams — tentatively scheduled for **Fridays of Week 3, 6, and 9**.

## Final Project

The final project will be a group data analysis project and consist of a poster session on the last day of class and short paper due during finals period. A proposal is due before the midterm break and will make up a portion of your grade.

## Communication

Assignments, note sets, and grades will be posted on Moodle. We will also use Ed for announcements, discussion, and homework questions. Please use Ed for any homework or course content questions; email me privately with any personal matters (grade discussions, illness, emergency, etc.). Any time-sensitive announcements will be posted on Ed. It is your responsibility to make sure that your notification settings allow time-sensitive announcements to reach you. 

# Grading Policies

Grades are an imperfect measure of learning, and no grading scheme will perfectly capture your "true" learning in this course. This grading scheme is designed to reward you for consistently participating, staying on top of the course material, and demonstrating proficiency with the content through in-class assessments.

Final grades will be calculated as follows:

-   15% Homework
-   50% Exams (16.66% each) 
-   15% Final Paper
-   10% Final Poster
- 	5% Daily check-ins (lowest 3 will be dropped)
- 	5% Attendance and participation in group work

More than 5 absences from class will result in a 0% attendance and participation grade. 

And letter grades will be assigned based on the usual grading scale (A = 93% and above, A- = 90-92.9%, B+ = 88-89.9%, B = 83-87.9%, etc.).

*A note on the "genius myth"*: I’ve found that many carls buy into the “genius myth” when it comes to math/stat courses: that you need to be a “math person” and have some innate mathematical ability in order to do well. This could not be further from the truth! The best statisticians don’t necessarily have the “best” math or programming background, but are people that are able to formulate interesting questions and use math and programming to answer those questions. Many of the best statisticians I know became statisticians because they were initially interested in something else (biology, public health, psychology, neuroscience, physics, etc.) and realized that being able to answer important questions with data was not only valuable but fun and interesting. Being able to perform interesting statistical analyses is a skill that is learned, not an innate ability, and working hard at developing that skill is the point of this course.

## Regrade requests

Grading is often a tedious task, and the grading team will sometimes make mistakes. I am always happy to fix these mistakes, and gradescope makes it easy to do so. Regrade requests must be submitted on gradescope within two weekdays after an assignment or exam has been returned to you. Regrade requests are for administrative errors or obvious grading mistakes. I will not consider regrade requests for anything that applied to the entire class (e.g. “I think this mistake should only be worth 1 point instead of 2” or “I didn’t realize we had to do X”). If you submit two or more inappropriate regrade requests, I will not consider additional regrade requests from you for the remainder of the term. If you’re unsure whether you should file a regrade request or not, just ask! You are always welcome to discuss any grading questions with me in office hours.

## Exam revisions

I offer the opportunity to submit exam revisions for two reasons: (1) to correct any major misunderstandings and have a chance to revisit material that you struggled with, (2) to mitigate the impact that a bad exam day can have on your final course grade. You can submit corrections to your exam to earn back 50% of your missed points. Corrected exam grades are capped at 80%. Exam revisions are due 1 week after graded exams are returned to you, or the last day of class at 11:59pm, whichever is earlier.

## Missing exams

If you miss a class when there is an exam, then there are no makeups offered. If must miss an exam due to an illness or other last minute emergency, please let me know in advance to arrange an alternative. 

# Academic Integrity

You are expected to follow Carleton’s [policies regarding academic integrity](https://www.carleton.edu/handbook/academics/?policy=329). I encourage you to discuss the homework problems with other humans and do background reading as needed. You should code and write up your solutions on your own. Exams must be done by yourself without communicating with others; all work must be your own. You should collaborate with your teammates on projects, and should use external resources for background research and debugging, but all work should be original and all sources should be properly cited. The use of textbook solution manuals (physical or online), course materials from other students, or materials from previous versions of this course are not allowed.

Large-language models (e.g. ChatGPT, Gemini, etc.) should only be used for coding or debugging help after you’ve attempted to solve the problem on your own, and you should never type homework problems directly into a prompt. Copying, paraphrasing, summarizing, or submitting work generated by anyone but yourself without proper attribution is considered academic dishonesty (this includes output from LLMs).

I also have a few rules in place to protect my intellectual property. You may not record my lectures using tools such as Otter.ai or upload any video or audio recordings to generate transcripts or study notes. You may not upload my course materials (slides, assignment prompts, note sets, etc.) into AI tools or homework help sites.

“AI” tools are new for all of us and it’s OK to have questions about what is and isn’t appropriate. Please ask if you are unsure of whether or not your actions are complying with the assignment/quiz/project instructions. Always default to acknowledging any help received. Cases of suspected academic dishonesty are handled by the Provost’s Office and I am obligated to report any suspected violations of this policy.

# Diversity and Inclusion

We all come to class with different backgrounds and experiences, and this diversity makes our class environment richer. I value diversity and inclusion, and am committed to a climate of mutual respect and full participation in and out of the classroom. This class strives to be a learning environment that is usable, equitable, inclusive and welcoming, regardless of race, ethnicity, religion, gender and gender identities, sexual orientation, ability, socioeconomic background, and nationality. If you anticipate or experience any barriers to learning, please discuss your concerns with me.

# Resources

## Professor availability

Please reach out to me if you have any questions! You can reach me on Ed, email, drop-in hours, or make an appointment. Ed is typically the best venue for homework/content questions outside of drop-in hours. I’ll respond to Ed messages at least 3 times each week day, and try to respond to emails within 48 hours You will receive responses faster on Ed than email. I am online irregularly over evenings and weekends to devote time to family and rest, and I hope that you also find time over the weekend to recharge and reset!

## Accomodations

Carleton College is committed to providing equitable access to learning opportunities for all students. The Office of Accessibility Resources (Henry House, 107 Union Street) is the campus office that collaborates with students who have disabilities to provide and/or arrange reasonable accommodations. If you have, or think you may have, a disability, please contact OAR\@carleton.edu to arrange a confidential discussion regarding equitable access and reasonable accommodations. You are also welcome to contact me privately to discuss your academic needs. However, all disability-related accommodations must be arranged, in advance, through OAR.

## Stat Lab

The Stats Lab (CMC 304) offers drop-in help R/RStudio help sessions run by friendly and knowledgeable lab assistants from 7-10pm Sunday through Thursday evenings.  To make the most of your time, attempt homework problems on your own beforehand and bring your class notes and lab manual as these are helpful references for both you and the lab assistant.

## Title IX

Please be aware that all faculty are “responsible employees”, which means that if you tell me about a situation involving sexual harassment, sexual assault, dating violence, domestic violence, or stalking, I must share that information with the Title IX Coordinator. Although I have to make this notification, you will control how your case will be handled, including whether or not you wish to meet with the Title IX coordinator or pursue a formal complaint.

## Take care of yourself

Do your best to maintain a healthy lifestyle this term by wearing a mask when you’re sick, eating a vegetable every now and then, exercising, avoiding excessive drug and alcohol use, getting enough sleep, and taking some time to relax. Your physical and mental health is more important than your grade in this course. There are many helpful resources available on campus and an important part of the college experience is learning how to ask for help. For more information, see Student Health and Counseling (SHAC), the Office of Health Promotion, or the Office of the Chaplain. If you are experiencing physical or mental health symptoms as a result of coursework, please speak with me so we can address the problem together.
