---
title: "Academic Honesty & Group Expectations"
---

```{r setup, include=FALSE, message=FALSE}
library(tidyverse)
library(bookdown)
library(infer)
library(ragg)
options(digits = 4)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = 'center', fig.width = 5, fig.height = 3, dev = ragg::agg_png())
notes_theme = theme_minimal(
 # base_family = "Montserrat", 
  base_size = 14)
theme_set(notes_theme)
```

The academic integrity policy for this class is listed below. Please read it and discuss the questions below.

> I encourage you to discuss the homework problems with others and use the resources available to you to try to figure out tough problems. You should code and write up your solutions on your own. Exams must be done by yourself without communicating with others; all work must be your own. The use of textbook solution manuals (physical or online), course materials from other students, or materials from previous versions of this course are not allowed. Large-language models (e.g. ChatGPT, Gemini, etc.) should only be used for coding help after you’ve attempted to solve the problem on your own, and you should never type homework problems directly into a prompt. Copying, paraphrasing, summarizing, or submitting work generated by anyone but yourself without proper attribution is considered academic dishonesty (this includes output from LLMs). 

> I also have a few rules in place to protect my intellectual property. You may not record my lectures using AI tools or upload any video or audio recordings to generate transcripts or study notes. You may not upload my course materials (slides, assignment prompts, note sets, etc.) into AI tools or homework help sites (such as chegg). 


> “AI” tools are new for all of us and it’s OK to have questions about what is and isn’t appropriate. Please ask if you are unsure of whether or not your actions are complying with the assignment/exam/project instructions. Always default to acknowledging any help received. Cases of suspected academic dishonesty are handled by the Provost’s Office and I am obligated to report any suspected violations of this policy. 


1. Does the policy make sense as written? Can you think of any "gray area" that it would be helpful to have clarified?

\vspace{1.25in}

2. Are there any examples of AI tools that you've found useful for learning that are *not* allowed in this class? What about any that *are* allowed?

\pagebreak

# Group Expectations

What makes group work successful? 

\vspace{2in}

What makes it unsuccessful? 

\vspace{2in}

What can you expect from each other? 

\vspace{2in}

What do you expect from Amanda? 





