---
title: "Notes 03: Experiments & Observational Studies"
---

```{r setup, include=FALSE, message=FALSE}
library(tidyverse)
options(digits = 4)
notes_theme = theme_minimal(base_size = 12, base_family = "Source Sans 3")
theme_set(notes_theme)
```

# Video Recap

::: callout-note
## Observational Study

Explanatory variable is only **observed** by researchers
:::

::: callout-note
## Experiment

- Explanatory Variable is **manipulated** by researchers
- Random Assignment (usually)
- Response Variable is measured
- With random assignment, any differences in the response variable between the groups is *caused* by the change in the explanatory variable
- Without random assignment, we have to be mindful of *confounding/lurking variables*
:::

::: callout-note
## Confounding Variable

**confounding variables** are other variables that are related to our explanatory variable that may be causing the difference in our response variable
:::

**Table of Conclusions:**

\vspace{3in}

# Warm Up

A recent article claims that “Green Spaces Make Kids Smarter”. The study described in the article involved a random sample of 2,263 schoolchildren in Barcelona. The researchers measured the amount of greenery around the children’s schools, and then measured the children’s working memories and attention spans. The children who had more vegetation around their schools did better on the memory and attention tests.

Summarize:

- The type of study (Experiment, Observational Study, or Sample Survey)
- The cases
- Response and Explanatory variables, and whether they’re categorical or quantitative
- Can the results be generalized to a population? If so, which? 
- Can causal conclusions be drawn? 

\vspace{2in}

# Activity

On moodle, navigate to the "Communicating Results Activity" and open the google slides presentation for further instructions.
