---
title: "Exam 3 Review"
---

```{r setup, include=FALSE, message=FALSE}
library(tidyverse)
library(bookdown)
library(infer)
library(ragg)
library(patchwork)
options(digits = 4)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = 'center', fig.width = 5, fig.height = 3, dev = ragg::agg_png())
notes_theme = theme_minimal(
 # base_family = "Montserrat", 
  base_size = 14)
theme_set(notes_theme)
```

**Big Idea:**

\pagebreak

**Variable types &rarr; test**

\pagebreak 

**Topics for Exam 3:**

1. So many distributions
    a) Population Distribution
    a) Sample distribution
    a) Sampling Distributions (CLT-based, bootstrap-based, and randomization-based)
1. Confidence Intervals
    a) Standard Deviation, Standard Error, and Margin of Error
    a) Interpreting in context
1. Hypothesis Tests
    a) Formulating null and alternative hypotheses
    a) Statistical significance and p-values
    a) Interpreting results in context
    a) Type I Error, Type II Error, and Power
    a) Connection to Confidence Intervals
1. CLT-based inference
    a) Proportions
    a) Means
    a) Difference in 2 proportions
    a) Difference in 2 means (independent groups and matched pairs)
    a) Multiple proportions ($\chi^2$)
    a) Multiple means (ANOVA)
    a) Inference for regression (Slope, CI for mean response, PI for individual response)

**Cheat Sheet:** You may bring 1 side of 1 standard 8.5x11 sheet of paper of notes, but no other materials are allowed. 

**Calculator:** I will bring basic calculators that you can use if you wish, but you may not use the calculator on your phone or any calculator that can make graphs or be programmed. 

**R Questions:** You won't be able to use your computer. The only R code you should be prepared to write down are probability calculations like `pnorm`, `qnorm`, `qt`, `pt`, `pchisq`, `pf`, etc. I will not give you R code and ask you to tell me what it does. You will be asked to look at output (e.g. a graph or `lm()` output) and interpret the results. 

**Academic Integrity:** I will ask you all to sign a statement that you have not received (and will not provide) any guidance or help on the exam problems, and will not discuss the exam with anyone inside or outside of class until it is returned to you. This includes using materials from prior versions of this class to study. Any academic integrity violations on the exam will be reported to the Provost's office.

**Additional Practice:** In addition to your notes, R activities in class, and homework; the "Unit C Essential Synthesis" and "Unit D Essential Synthesis" of the textbook provides a nice overview and some conceptual practice problems. *Note:* don't over-study these practice problems, since the format of the exam will be entirely different. Focus your time and energy on understanding notes and homework problems first.

**Format of the exam:** The exam will be similar to the first exam and follow the "data analysis" format. 


