---
title: "Exam III Corrections"
---

I offer exam corrections for two reasons: 

 1. To correct any major misunderstandings and have a chance to revisit material that you struggled with
 2. To mitigate the impact that a bad exam day can have on your course grade
 
You can submit corrections to your exam to earn back 50% of your missed points. Corrected exam grades are capped at **85%**. (If you scored above or near this number, you did great! Neither point (1) or (2) applies to you)

::: {.callout-warning appearance="default"}
## Please read these directions carefully!

You won't earn back full points if you don't follow these directions.
:::


If you'd like to submit corrections, please start by printing your exam from gradescope. You will correct your answers directly on the original copy (this lets me see your original and corrected answers in the same place) include the following for each question that you would like to resubmit: 

 (a) Your original answer (if you use your graded exam from gradescope, this is already there for you!)
 (b) Your corrected answer (should _not_ be identical to feedback provided on your graded exam)
 
  - For open‐ended questions: your corrected answer
  - For T/F questions or “check the box” questions: your corrected answer plus an explanation
  - For Q5 i‐v: your corrected answer, plus an appropriate null and alternative hypothesis

 (c) An example/practice problem from homework, daily prep, notes, or the book that a future student could study to understand the exam problem.

Once you are done with your revisions, please complete the [Exam Revisions Cover Sheet](https://docs.google.com/document/d/1O6BPWJgAA3gjz20lHg2HmNQusoURXvLzkqNyFFOs6qc/edit?usp=sharing) and print. 

You should submit a corrected exam **on paper** by **4pm on Wednesday**. You should hand them to Amanda either before class or during office hours.
