---
title: "Exam II Corrections"
---

I offer exam corrections for two reasons: 

 1. To correct any major misunderstandings and have a chance to revisit material that you struggled with
 2. To mitigate the impact that a bad exam day can have on your course grade
 
You can submit corrections to your exam to earn back 50% of your missed points. Corrected exam grades are capped at **86%**. (If you scored above or near this number, you did great! Neither point (1) or (2) applies to you)



::: {.callout-warning appearance="default"}
## Please read these directions carefully!

You won't earn back full points if you don't follow these directions.
:::

If you'd like to submit corrections, please start by printing your exam from gradescope. You will correct your answers directly on the original copy (this lets me see your original and corrected answers in the same place) include the following for each question that you would like to resubmit: 

 (a) Your corrected answer (please don't use grading comments verbatim)
 
  - For open‐ended questions: your corrected answer is sufficient
  - For T/F questions or “check the box” questions: your corrected answer plus an explanation

 (b) Refer to a set of slides, notes, in class activity, or homework problem that includes the relevant topic. (e.g. what would you suggest a future student study to not make the same mistake)

You should submit a corrected exam **on paper** by **Friday of Week 5 at 5pm**. You should hand them to Amanda either before or after class or during office hours.

